To review
okaufman/CleanUpSessions pull request #2
Opened 2019-03-05 09:29 UTC by okaufman

2019-03-09 17:26 UTC, Amstutz requested changes
Hallo Olivia

Ich habe einige Kommentare hinterlasse, bitte überarbeiten. Wichtig:
- [ ] einige (GUI) Klassen scheinen überflüssig. Bitte schreib bei *jeder* Klasse kurz was sie tut und weshalb es sie gibt.
- [ ] Die intendations sind an vielen stellen seltsam, bitte korrigiern.

2019-03-09 17:26 UTC, Amstutz commented on README.md
> +```
Das ist ein Cron Plugin, wie aktiviert man Cron und wie dieses Plugin, bitte hier beschreiben.

2019-03-09 17:26 UTC, Amstutz commented on classes/class.cleanUpSessionsConfigGUI.php
> +	protected $access;
Die wird nur an einem Ort verwendet, nur dort initialisieren.

2019-03-09 17:26 UTC, Amstutz commented on classes/class.cleanUpSessionsConfigGUI.php
> +		$tpl->setContent($form->getHTML());
DIC verwenden.

2019-03-09 17:26 UTC, Amstutz commented on classes/class.cleanUpSessionsConfigGUI.php
> +	protected function checkAndUpdate($expiration_value) {
was ist der Typ von expiration value, hier type hinten (e.g. int $expiration_value)

2019-03-09 17:26 UTC, Amstutz commented on classes/class.cleanUpSessionsConfigGUI.php
> +class cleanUpSessionsConfigGUI extends cleanUpSessionsMainGUI {
Wieso gibt es diese Klasse. Wieso extended sie cleanUpSessionMainGUI? was ist der Unterschied zu ilCleanUpSessionsConfigGUI?

2019-03-09 17:26 UTC, Amstutz commented on classes/class.cleanUpSessionsMainGUI.php
> +class cleanUpSessionsMainGUI {
Wieso gibt es diese Klasse? Was ist der Unterschied zu ilCleanUpSessionsConfigGUI?

2019-03-09 17:26 UTC, Amstutz commented on classes/uninstall/class.cleanUpSessionsRemoveDataConfirm.php
> +class CleanUpSessionsRemoveDataConfirm {
Was tut diese Klasse? Wieso sind (fast) alle Methoden nicht implementiert?

2019-03-09 17:26 UTC, Amstutz commented on src/Helper/cleanUpSessionsDBAccess.php
> +		$this->logger->pushHandler($this->streamHandler, Logger::DEBUG);
Intendations sind komisch hier? nutzt du tabas oder spaces?

2019-03-12 15:00 UTC, okaufman commented on classes/class.cleanUpSessionsConfigGUI.php
> +	protected $access;
erledigt

2019-03-12 15:00 UTC, okaufman commented on classes/class.cleanUpSessionsConfigGUI.php
> +		$tpl->setContent($form->getHTML());
erledigt

2019-03-12 15:01 UTC, okaufman commented on README.md
> +```
Readme überarbeitet

2019-03-12 15:01 UTC, okaufman commented on classes/class.cleanUpSessionsConfigGUI.php
> +	protected function checkAndUpdate($expiration_value) {
erledigt

2019-03-12 15:26 UTC, okaufman commented on src/Helper/cleanUpSessionsDBAccess.php
> +		$this->logger->pushHandler($this->streamHandler, Logger::DEBUG);
Ich habe den Code reformatiert mit tab's.

2019-03-18 14:29 UTC, okaufman commented on classes/uninstall/class.cleanUpSessionsRemoveDataConfirm.php
> +class CleanUpSessionsRemoveDataConfirm {
Ich habe die Klasse gelöscht

2019-03-25 10:10 UTC, okaufman commented on classes/class.cleanUpSessionsMainGUI.php
> +class cleanUpSessionsMainGUI {
Ich habe jetzt die Funktionalitäten dieser Klasse(saveConfig, checkandUpdate, cancel, index) zu ilCleanUpSessionsConfigGUI kopiert und cleanUpSessionsMainGUI gelöscht. Jetzt habe ich nur noch eine GUI Klasse.

2019-03-25 10:25 UTC, okaufman commented on classes/class.cleanUpSessionsConfigGUI.php
> +class cleanUpSessionsConfigGUI extends cleanUpSessionsMainGUI {
Ich habe diese Klasse gelöscht

2019-10-23 08:26 UTC, closed without merging